apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: nginx-deployment
  namespace: tst
  labels:
    app: nginx
    environment: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx 
      environment: production
  template:
    metadata:
      labels:
        app: nginx
        environment: production
    spec:
      containers:
        - name: nginx-containers
          image: CONTAINER_IMAGE
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: tst
  labels:
    app: nginx 
    environment: production
spec:
  type: LoadBalancer
  selector:
    app: nginx 
    environment: production
  ports:
    - port: 80
      targetPort: 80 